### ISSUE TITLE
error while reproducing results (llm_math_judge)

### ISSUE THREAD

**Issue by yacinedolivet** [Kipok/NeMo-Skills#185]
hi, i've followed the steps indicated in `reproducing-results.md`. For generating the greedy results i did run only math and gsm8k with 

```ns eval \
    --cluster=local \
    --model=/workspace/openmath2-llama3.1-8b-trtllm \
    --server_type=trtllm \
    --output_dir=/workspace/openmath2-llama3.1-8b-eval \
    --benchmarks=math:0,gsm8k:0 \
    --server_gpus=1 \
    --num_jobs=1 \
    ++prompt_template=llama3-instruct \
    ++batch_size=512 \
    ++inference.tokens_to_generate=4096```

and it completes fine

now for the judge step i did run 

```ns llm_math_judge \
    --cluster=local \
    --model=gpt-4o \
    --server_type=openai \
    --server_address=https://api.openai.com/v1 \
    --input_files="/workspace/openmath2-llama3.1-8b-eval/eval-results/**/output*.jsonl"```

however i am getting the following error

```
Error executing job with overrides: ['++input_files=/workspace/openmath2-llama3.1-8b-eval/eval-results/**/output*.jsonl', '++server.server_type=openai', '++server.base_url=https://api.openai.com/v1', '++server.mod>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 93, in handle_request
    self._send_request_headers(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 151, in _send_request_headers
    with map_exceptions({h11.LocalProtocolError: LocalProtocolError}):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.LocalProtocolError: Illegal header value b'Bearer '

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 981, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.LocalProtocolError: Illegal header value b'Bearer '

The above exception was the direct cause of the following exception:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nemo_run/code/nemo_skills/inference/llm_math_judge.py", line 164, in llm_math_judge
    outputs = llm.generate(
  File "/nemo_run/code/nemo_skills/inference/server/model.py", line 297, in generate
    outputs = [{'generation': future.result()} for future in futures]
  File "/nemo_run/code/nemo_skills/inference/server/model.py", line 297, in <listcomp>
    outputs = [{'generation': future.result()} for future in futures]
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nemo_run/code/nemo_skills/inference/server/model.py", line 392, in _send_request
    response = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 704, in create
    return self._post(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1268, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 945, in request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1005, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1083, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1005, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1083, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1015, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```
did i miss some step in the setup ?

**Comment by Kipok** [comment]
Thanks for reporting this and sorry about the obscure error message. Most likely reason is that you didn't define OPENAI_API_KEY environment variable which is required for that script to work. Can you please define it and retry?

**Comment by Kipok** [comment]
Merged an update that should make error message better and also added it in the docs https://github.com/Kipok/NeMo-Skills/pull/186

**Comment by yacinedolivet** [comment]
thanks a lot, i made an api key but am hitting a throttling error from openai

```nemo-run-0/0 openai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-2gybi91K3zdFMlTRSsKAHGSb on tokens per min (TPM): Limit 30000, Used 27341, Requested 2723. Please try again in 128ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
```

would be great to offer a setting to manage the maximum nb of request per seconds maybe ?

**Comment by Kipok** [comment]
You can control this (to some degree) with `++batch_size` parameter. E.g. if you set `++batch_size=1` it will only submit the next request after the current one is finished. There is also an option to use batched api, which has much higher limits, but it's not exposed (yet) in the llm-math-judge script.

By the way, if you're only interested in math/gsm8k, you don't really need to use the judge. The numbers from our symbolic checker are going to be very close to the judge evaluation for those benchmarks, so you can skip that step and run summarize_results right away

**Comment by yacinedolivet** [comment]
hi Igor,

thanks a lot first of all for being so responsive this is super appreciated!

to give you a little bit of context, 2 classmates and I from stanford are doing an ML project for our class cs230 on the topic of math problems resolution and we found your results very impressive. That and the fact that you took the pain to offer some precise instructions on how to reproduce your results motivated us a lot to make the jump and try to do it for ourselves and perhaps base our next steps on your framework

thanks for the remarks on openai so perhaps it is not crucial for us to make use of the openai gpt as a judge. i will also play with those params you suggest

thanks a lot once again and perhaps we will share some of our results with you if you are interested!

best

Yacine

**Comment by Kipok** [comment]
Sounds good! Glad that you found this work helpful and hope you can indeed use our code for your project. Let us know if you run into any issues along the way
